QA: bug when disk_count == 1 . disk_2_count needs to be 0
Bug fixed. disk_2_count needs to be 0.

Traceback (most recent call last):
  File "./stgadm.py", line 9, in <module>
    main_menu()
  File "/opt/STGAdm/stgadm/menu.py", line 498, in main_menu
    stg_type, stg_sid, wwn_client)
  File "/opt/STGAdm/stgadm/menu.py", line 397, in menu_ibm_ds8k
    new_change.preview()
  File "/opt/STGAdm/stgadm/ds8k_add_dev.py", line 75, in preview
    self.disk_1_count + self.disk_2_count))
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'