Fixed bug SyntaxError for DS8K and improve of fields
Fixed bug of SyntaxError for execute changes when the
host client contains character '-' on the name on
IBM DS8K.

Before of this change the operator was:
change_primary pool_host client_date

now is only change_date to prevent this error

'''
Select the Change/Ticket/WO to execute:

0 : change_WO0000000064019_1_DBSERVER01_HBA0-LVM_V12_04182016_104738.py
1 : change_WO0000000064019_2_DBSERVER02_HBA0-LVM_V14_04182016_105532.py

What's change/ticket id you want execute?: 1
Traceback (most recent call last):
  File "./stgadm.py", line 9, in <module>
    main_menu()
  File "/opt/STGAdm/stgadm/menu.py", line 587, in main_menu
    'stgadm.changes.{0}'.format(change_file))
  File "/usr/lib/python2.6/site-packages/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/STGAdm/stgadm/changes/change_WO0000000064019_2_DBSERVER02_HBA0-LVM__V14_04182016_105532.py", line 37
    WO0000000064019_2_P0_DBSERVER02_HBA0-LVM__04182016_105532 = ds8k_add_dev.New(
SyntaxError: can't assign to operator
'''

The change and others fields were also improved on this review

Change-Id: I6caee6dc25a4eefbb83b4ed261843f16902ef6c2